[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = subject
x509_extensions = extensions

[subject]
C = CR
ST = San Jose
L = San Jose
O = Universidad Latina
OU = Sistemas Operativos II
CN = plataforma.local

[extensions]
subjectAltName = @alt_names
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth

[alt_names]
DNS.1 = plataforma.local
DNS.2 = localhost
IP.1 = 127.0.0.1
